---
# Defines the configuration for the 'kind' (Kubernetes in Docker) cluster.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Configures the cluster's main control-plane node.
  - role: control-plane
    # Forwards local machine (host) ports to the cluster's internal node.
    extraPortMappings:
      # Exposes the application service on http://localhost:8080.
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # Exposes the Prometheus UI on http://localhost:9090.
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
      # Exposes the Grafana UI on http://localhost:3000.
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
